/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_nowireless_kinect_internal_Native */

#ifndef _Included_org_nowireless_kinect_internal_Native
#define _Included_org_nowireless_kinect_internal_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_nowireless_kinect_internal_Native
 * Method:    freenectInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_nowireless_kinect_internal_Native_freenectInit
  (JNIEnv *, jclass);

/*
 * Class:     org_nowireless_kinect_internal_Native
 * Method:    freenectSetLogLevel
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_nowireless_kinect_internal_Native_freenectSetLogLevel
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_nowireless_kinect_internal_Native
 * Method:    freenectProcessEvents
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_nowireless_kinect_internal_Native_freenectProcessEvents
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_nowireless_kinect_internal_Native
 * Method:    freenectNumDevices
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_nowireless_kinect_internal_Native_freenectNumDevices
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_nowireless_kinect_internal_Native
 * Method:    freenectOpenDevice
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_nowireless_kinect_internal_Native_freenectOpenDevice
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_nowireless_kinect_internal_Native
 * Method:    freenectCloseDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_nowireless_kinect_internal_Native_freenectCloseDevice
  (JNIEnv *, jclass);

/*
 * Class:     org_nowireless_kinect_internal_Native
 * Method:    freenectStartDepth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_nowireless_kinect_internal_Native_freenectStartDepth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_nowireless_kinect_internal_Native
 * Method:    freenectStartVideo
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_nowireless_kinect_internal_Native_freenectStartVideo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_nowireless_kinect_internal_Native
 * Method:    freenectStopDepth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_nowireless_kinect_internal_Native_freenectStopDepth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_nowireless_kinect_internal_Native
 * Method:    freenectStopVideo
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_nowireless_kinect_internal_Native_freenectStopVideo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_nowireless_kinect_internal_Native
 * Method:    freenectSetTiltDegs
 * Signature: (JD)I
 */
JNIEXPORT jint JNICALL Java_org_nowireless_kinect_internal_Native_freenectSetTiltDegs
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     org_nowireless_kinect_internal_Native
 * Method:    freencetTiltStatusCode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_nowireless_kinect_internal_Native_freencetTiltStatusCode
  (JNIEnv *, jclass);

/*
 * Class:     org_nowireless_kinect_internal_Native
 * Method:    freenectSetLed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_nowireless_kinect_internal_Native_freenectSetLed
  (JNIEnv *, jclass);

/*
 * Class:     org_nowireless_kinect_internal_Native
 * Method:    freenectGetVideoModeCount
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_nowireless_kinect_internal_Native_freenectGetVideoModeCount
  (JNIEnv *, jclass);

/*
 * Class:     org_nowireless_kinect_internal_Native
 * Method:    freenectGetDepthModeCount
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_nowireless_kinect_internal_Native_freenectGetDepthModeCount
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
